"""NSE F&O stock universe used by the scanner.

The universe contains the individual-security F&O symbols published by NSE,
plus securities introduced into the F&O segment during 2026. Index symbols are
intentionally excluded because the scanner is for stocks.
"""

NSE_FNO_SYMBOLS = [
    "AARTIIND", "ABB", "ABBOTINDIA", "ACC", "ADANIENT", "ADANIPORTS",
    "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "ABCAPITAL", "ABFRL", "ALKEM",
    "AMBUJACEM", "ANGELONE", "APLAPOLLO", "APOLLOHOSP", "APOLLOTYRE",
    "ASHOKLEY", "ASIANPAINT", "ASTRAL", "ATUL", "AUBANK", "AUROPHARMA",
    "AXISBANK", "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BALKRISIND",
    "BALRAMCHIN", "BANDHANBNK", "BANKBARODA", "BATAINDIA", "BERGEPAINT",
    "BEL", "BHARATFORG", "BHEL", "BPCL", "BHARTIARTL", "BIOCON", "BSOFT",
    "BOSCHLTD", "BRITANNIA", "CANFINHOME", "CANBK", "CHAMBLFERT", "CHOLAFIN",
    "CIPLA", "CUB", "COALINDIA", "COFORGE", "COLPAL", "CONCOR", "COROMANDEL",
    "CROMPTON", "CUMMINSIND", "DABUR", "DALBHARAT", "DEEPAKNTR", "DELTACORP",
    "DIVISLAB", "DIXON", "DLF", "LALPATHLAB", "DRREDDY", "EICHERMOT", "ESCORTS",
    "EXIDEIND", "GAIL", "GLENMARK", "GMRINFRA", "GODREJCP", "GODREJPROP",
    "GRANULES", "GRASIM", "GUJGASLTD", "GNFC", "HAVELLS", "HCLTECH", "HDFCAMC",
    "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", "HINDALCO", "HAL", "HINDCOPPER",
    "HINDPETRO", "HINDUNILVR", "HDFC", "ICICIBANK", "ICICIGI", "ICICIPRULI",
    "IDFCFIRSTB", "IDFC", "IBULHSGFIN", "INDIAMART", "IEX", "IOC", "IRCTC", "IGL",
    "INDUSTOWER", "INDUSINDBK", "NAUKRI", "INFY", "INTELLECT", "INDIGO", "IPCALAB",
    "ITC", "JINDALSTEL", "JKCEMENT", "JSWSTEEL", "JUBLFOOD", "KOTAKBANK", "L&TFH",
    "LTTS", "LTIM", "LT", "LAURUSLABS", "LICHSGFIN", "LUPIN", "MGL", "M&MFIN",
    "M&M", "MANAPPURAM", "MARICO", "MARUTI", "MFSL", "METROPOLIS", "MOTHERSON",
    "MPHASIS", "MRF", "MCX", "MUTHOOTFIN", "NATIONALUM", "NAVINFLUOR", "NESTLEIND",
    "NMDC", "NTPC", "OBEROIRLTY", "ONGC", "OFSS", "PAGEIND", "PERSISTENT",
    "PETRONET", "PIIND", "PIDILITIND", "PEL", "POLYCAB", "PFC", "POWERGRID", "PNB",
    "PVRINOX", "RAIN", "RBLBANK", "RECLTD", "RELIANCE", "SBICARD", "SBILIFE",
    "SHREECEM", "SHRIRAMFIN", "SIEMENS", "SRF", "SBIN", "SAIL", "SUNPHARMA",
    "SUNTV", "SYNGENE", "TATACHEM", "TATACOMM", "TCS", "TATACONSUM", "TATAMOTORS",
    "TATAPOWER", "TATASTEEL", "TECHM", "FEDERALBNK", "INDIACEM", "INDHOTEL",
    "RAMCOCEM", "TITAN", "TORNTPHARM", "TRENT", "TVSMOTOR", "ULTRACEMCO", "UBL",
    "MCDOWELL-N", "UPL", "VEDL", "IDEA", "VOLTAS", "WHIRLPOOL", "WIPRO", "ZEEL",
    "ZYDUSLIFE",
    # 2026 additions / current F&O names
    "COCHINSHIP", "HYUNDAI", "MOTILALOFS", "NAM-INDIA", "VMM", "FORCEMOT",
    "GODFRYPHLP", "DEVYANI", "ADANIGREEN", "ADANIENSOL", "INOXWIND", "NBCC",
    "PATANJALI", "SAMMAANCAP",
]

# Remove accidental duplicates while preserving order.
NSE_FNO_SYMBOLS = list(dict.fromkeys(NSE_FNO_SYMBOLS))
